"""Initial migration

Revision ID: dbaf859e42c6
Revises: 
Create Date: 2026-04-29 01:43:51.478044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbaf859e42c6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False, comment='Уникальный идентификатор продукта'),
    sa.Column('name', sa.String(length=128), nullable=False, comment='Название продукта'),
    sa.Column('calories_per_100g', sa.Float(), nullable=False, comment='Калории на 100 г продукта'),
    sa.Column('proteins_per_100g', sa.Float(), nullable=False, comment='Белки (г) на 100 г продукта'),
    sa.Column('fats_per_100g', sa.Float(), nullable=False, comment='Жиры (г) на 100 г продукта'),
    sa.Column('carbs_per_100g', sa.Float(), nullable=False, comment='Углеводы (г) на 100 г продукта'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_name'), ['name'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False, comment='Уникальный идентификатор пользователя'),
    sa.Column('username', sa.String(length=64), nullable=False, comment='Имя пользователя для входа'),
    sa.Column('password_hash', sa.String(length=128), nullable=False, comment='Хеш пароля пользователя'),
    sa.Column('role', sa.String(length=20), nullable=False, comment='Роль пользователя в системе'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_name'))

    op.drop_table('products')
    # ### end Alembic commands ###
