"""Add ration models

Revision ID: ea960cbff56e
Revises: 03c4030295a6
Create Date: 2026-04-29 01:56:01.137973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea960cbff56e'
down_revision = '03c4030295a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rations',
    sa.Column('id', sa.Integer(), nullable=False, comment='Уникальный идентификатор рациона'),
    sa.Column('date', sa.Date(), nullable=False, comment='Дата, за которую составлен рацион'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='Идентификатор пользователя, к которому относится рацион'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rations_date'), ['date'], unique=False)

    op.create_table('ration_items',
    sa.Column('id', sa.Integer(), nullable=False, comment='Уникальный идентификатор элемента рациона'),
    sa.Column('weight', sa.Float(), nullable=False, comment='Вес продукта в данном приеме пищи (в граммах)'),
    sa.Column('ration_id', sa.Integer(), nullable=False, comment='Идентификатор рациона, к которому относится элемент'),
    sa.Column('product_id', sa.Integer(), nullable=False, comment='Идентификатор продукта в этом элементе'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['ration_id'], ['rations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ration_items')
    with op.batch_alter_table('rations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rations_date'))

    op.drop_table('rations')
    # ### end Alembic commands ###
