"""Final schema with profiles and expanded logic

Revision ID: f6d8c9a3b2e4
Revises: ea960cbff56e
Create Date: 2026-05-02 14:35:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6d8c9a3b2e4'
down_revision = 'ea960cbff56e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False, comment='Заголовок статьи'),
    sa.Column('content', sa.Text(), nullable=False, comment='Текст статьи'),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=256), nullable=False, comment='Описание действия'),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='IP адрес инициатора'),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('health_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('goal_type', sa.String(length=50), nullable=False),
    sa.Column('target_weight', sa.Float(), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True, comment='Возраст пользователя'),
    sa.Column('weight', sa.Float(), nullable=True, comment='Вес в килограммах'),
    sa.Column('height', sa.Float(), nullable=True, comment='Рост в сантиметрах'),
    sa.Column('gender', sa.String(length=10), nullable=True, comment='Пол (male/female)'),
    sa.Column('activity_level', sa.Float(), nullable=True, comment='Коэффициент физической активности'),
    sa.Column('target_calories', sa.Float(), nullable=True, comment='Целевая калорийность'),
    sa.Column('target_protein', sa.Float(), nullable=True, comment='Целевой белок'),
    sa.Column('target_fat', sa.Float(), nullable=True, comment='Целевые жиры'),
    sa.Column('target_carbs', sa.Float(), nullable=True, comment='Целевые углеводы'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feedbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('ration_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True, comment='Оценка точности системы (1-5)'),
    sa.Column('comment', sa.Text(), nullable=True, comment='Комментарий пользователя'),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ration_id'], ['rations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True, comment='Дата регистрации'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    op.drop_table('feedbacks')
    op.drop_table('user_profiles')
    op.drop_table('health_goals')
    op.drop_table('audit_logs')
    op.drop_table('articles')
    # ### end Alembic commands ###
